"""add devices table

Revision ID: c4a992515ba2
Revises: 21016a5ba037
Create Date: 2026-07-31 16:51:24.757677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4a992515ba2'
down_revision: Union[str, Sequence[str], None] = '21016a5ba037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('ANDROID', 'IOS', 'WEB', name='deviceplatform'), nullable=False),
    sa.Column('device_name', sa.String(length=150), nullable=True),
    sa.Column('push_token', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_push_token'), 'devices', ['push_token'], unique=True)
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.alter_column('vaccination_records', 'vaccine_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('vaccination_records', 'is_administered',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vaccination_records', 'facility_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('vaccination_records', 'healthcare_provider',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('vaccination_records', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_vaccination_child_administered'), table_name='vaccination_records')
    op.drop_index(op.f('ix_vaccination_child_schedule'), table_name='vaccination_records')
    op.alter_column('vaccination_reminders', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SENT', 'DISMISSED', name='reminderstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vaccination_reminders', 'channel',
               existing_type=postgresql.ENUM('PUSH', 'EMAIL', 'SMS', name='reminderchannel'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vaccination_reminders', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_vaccination_reminder_date'), table_name='vaccination_reminders')
    op.create_index(op.f('ix_vaccination_reminders_reminder_date'), 'vaccination_reminders', ['reminder_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vaccination_reminders_reminder_date'), table_name='vaccination_reminders')
    op.create_index(op.f('ix_vaccination_reminder_date'), 'vaccination_reminders', ['reminder_date'], unique=False)
    op.alter_column('vaccination_reminders', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('vaccination_reminders', 'channel',
               existing_type=postgresql.ENUM('PUSH', 'EMAIL', 'SMS', name='reminderchannel'),
               server_default=sa.text("'PUSH'::reminderchannel"),
               existing_nullable=False)
    op.alter_column('vaccination_reminders', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SENT', 'DISMISSED', name='reminderstatus'),
               server_default=sa.text("'PENDING'::reminderstatus"),
               existing_nullable=False)
    op.create_index(op.f('ix_vaccination_child_schedule'), 'vaccination_records', ['child_id', 'scheduled_date'], unique=False)
    op.create_index(op.f('ix_vaccination_child_administered'), 'vaccination_records', ['child_id', 'administered_date'], unique=False)
    op.alter_column('vaccination_records', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('vaccination_records', 'healthcare_provider',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('vaccination_records', 'facility_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('vaccination_records', 'is_administered',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('vaccination_records', 'vaccine_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_push_token'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
